## Evaluating single- and multi-task profile model in PyTorch with Katie's data loading

**Author:** Alex Tseng (amtseng@stanford.edu) -- Modified by Katie Spivakovsky

In [1]:
# modify this for your own machine
%env CUDA_VISIBLE_DEVICES = 1
%config Completer.use_jedi = False

from importlib import reload
import pandas as pd
import sys
sys.path.append('/home/katie/bp_repo/multitask_profile_model_SPI_GATA/')
import all_functions
from all_functions import *

env: CUDA_VISIBLE_DEVICES=1


In [2]:
ctcf = pd.read_csv('/home/katie/bp_repo/research/data/cutnrun/temp/fragment_lengths/CTCF_frag_lengths.txt',header=None)[0]
ctcf = np.array(ctcf).reshape((-1,1))
fosl = pd.read_csv('/home/katie/bp_repo/research/data/cutnrun/temp/fragment_lengths/FOSL2_frag_lengths.txt',header=None)[0]
fosl = np.array(fosl).reshape((-1,1))

In [3]:
ctcf.shape

(39478628, 1)

In [10]:
fosl.shape

(22967252, 1)

In [6]:
sum(ctcf <= 120)

array([8309680])

In [7]:
sum(ctcf >= 150)

array([27456078])

In [12]:
27456078/8309680

3.3041077394075344

In [8]:
sum(fosl <= 120)

array([7775720])

In [9]:
sum(fosl >= 150)

array([13602654])

In [13]:
13602654 / 7775720

1.749375491915861

In [2]:
set_num_epochs(10)

In [3]:
set_tasks_path('/home/katie/bp_repo/research/data/cutnrun/')

In [4]:
get_tasks_path()

'/home/katie/bp_repo/research/data/cutnrun/'

In [5]:
import datetime

In [8]:
evaluate?

Signature:
evaluate(
    train_tasks,
    val_tasks,
    test_tasks,
    num_tasks,
    assay,
    controls=True,
    epoch_metrics=False,
    initialize_state_dict=None,
    train_dset=None,
    val_dset=None,
    test_dset=None,
    train_loader=None,
    val_loader=None,
    test_loader=None,
    statuses=None,
    model_task_statuses=None,
    model_save_path=None,
)
Docstring:
Given tasks, return a list with the loss (after each epoch) and performance metrics
Args:
train_tasks: list of task names, e.g. ['SPI1', 'GATA2']
val_tasks: same as train_tasks
test_tasks: same as train_tasks
num_tasks: number of tasks (kinda redundant info, I may just remove this later)
assay (str): either 'cutnrun' or 'chip-seq' (or some variation in those spellings)
controls: whether or not to use controls
epoch_metrics: whether or not to compute metrics after each epoch
initialize_state_dict: path to state_dict if you want to initialize model with specific weights

Optional (but must include all if you i

In [25]:
start = datetime.datetime.now()
tasks = ['FOSL2_120','FOSL2_150']
METRICS, LOSSES = evaluate(tasks, tasks, tasks, 2, 'cutnrun', False,
                           statuses=statuses, model_task_statuses=model_task_statuses,
                          model_save_path='/home/katie/bp_repo/research/trained_models/FOSL2_10_epochs_cutnrun_multi_task_AUG8.model')
datetime.datetime.now() - start

FOSL2_120 BED path: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2.bed
FOSL2_150 BED path: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2.bed
Negative FOSL2 BigWig: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2_merged_maxfl120_neg.bw
Positive FOSL2 BigWig: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2_merged_maxfl120_pos.bw
Negative FOSL2 BigWig: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2_merged_minfl150_neg.bw
Positive FOSL2 BigWig: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2_merged_minfl150_pos.bw
Negative FOSL2 BigWig: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2_merged_maxfl120_neg.bw
Positive FOSL2 BigWig: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2_merged_maxfl120_pos.bw
Negative FOSL2 BigWig: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2_merged_minfl150_neg.bw
Positive FOSL2 BigWig: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2_merged_minfl150_pos.bw
Negative FOSL2 BigWig: /home/katie/bp_repo/r

	Loss: ----:   0%|          | 0/577 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/73 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/577 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/73 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/577 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/73 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/577 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/73 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/577 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/73 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/577 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/73 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/577 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/73 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/577 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/73 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/577 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/73 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/577 [00:00<?, ?it/s]

	Loss: ----:   0%|          | 0/73 [00:00<?, ?it/s]

  0%|          | 0/64 [00:00<?, ?it/s]

		Computing profile NLL and cross entropy... 1s
		Computing profile JSD... 3s
		Computing profile correlations/MSE... 13s
		Separating tasks and computing count correlations/MSE... 0s


datetime.timedelta(seconds=550, microseconds=514544)

In [6]:
ctcf_cutnrun_train = DataLoader(['CTCF_120'],'cutnrun',False,
           '/home/katie/bp_repo/research/data/cutnrun/', ['train','val','test'])

In [10]:
ctcf_cutnrun_train = DataLoader(['CTCF_150'],'cutnrun',False,
           '/home/katie/bp_repo/research/data/cutnrun/', ['train','val','test'])

In [ ]:
model_task_statuses, statuses = loader.make_statuses()

In [ ]:
## ChIP-seq

In [ ]:
tasks_path = 'data/chip-seq/'
set_tasks_path(tasks_path)

In [ ]:
## CUT&RUN

In [9]:
tasks_path = 'data/cutnrun/'
set_tasks_path(tasks_path)

In [16]:
fosl_cutnrun_multitask_loader = DataLoader(['FOSL2_120','FOSL2_150'], 'cutnrun',
                                   False, '/home/katie/bp_repo/research/data/cutnrun/', ['full'])

In [17]:
fosl_cutnrun_multitask = fosl_cutnrun_multitask_loader.make_loaders()

FOSL2_120 BED path: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2.bed
FOSL2_150 BED path: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2.bed
Negative FOSL2 BigWig: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2_merged_maxfl120_neg.bw
Positive FOSL2 BigWig: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2_merged_maxfl120_pos.bw
Negative FOSL2 BigWig: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2_merged_minfl150_neg.bw
Positive FOSL2 BigWig: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2_merged_minfl150_pos.bw


In [19]:
model_task_statuses, statuses = fosl_cutnrun_multitask_loader.make_statuses()
statuses = statuses['full']

FOSL2_120 BED path: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2.bed
FOSL2_150 BED path: /home/katie/bp_repo/research/data/cutnrun/FOSL2/FOSL2.bed


In [ ]:
# chip-seq no controls
dl_dict = {'CTCF': [ctcf_chip_seq_no_controls_loader, 
                    ctcf_chip_seq_no_controls_train_loader, 
                    ctcf_chip_seq_no_controls_test_loader],
           'FOSL2': [fosl_chip_seq_no_controls_loader,
                     fosl_chip_seq_no_controls_train_loader,
                     fosl_chip_seq_no_controls_test_loader]}

In [ ]:
# chip-seq with controls
dl_dict = {'CTCF': [ctcf_chip_seq_loader, 
                    ctcf_chip_seq_train_loader, 
                    ctcf_chip_seq_test_loader],
           'FOSL2': [fosl_chip_seq_loader,
                     fosl_chip_seq_train_loader,
                     fosl_chip_seq_test_loader]}

In [ ]:
# cutnrun (no controls, duh)
dl_dict = {'CTCF': [ctcf_cutnrun_loader, 
                    ctcf_cutnrun_train_loader, 
                    ctcf_cutnrun_test_loader],
           'FOSL2': [fosl_cutnrun_loader,
                     fosl_cutnrun_train_loader,
                     fosl_cutnrun_test_loader]}

In [ ]:
r1 = ['Epoch 1', 'Epoch 2', 'Epoch 3', 'Epoch 4', 'Epoch 5', 'Epoch 6', 'Epoch 7', 'Epoch 8', 'Epoch 9', 'Epoch 10']
r2 = ['Full', 'Train', 'Test']
r3 = ['profile NLL','profile cross entropy','profile JSD',
            'profile Pearson','profile Spearman','profile MSE',
            'count Pearson','count Spearman','count MSE']
rows_metrics = pd.MultiIndex.from_product((r1, r2, r3))

r1 = ['Epoch 1', 'Epoch 2', 'Epoch 3', 'Epoch 4', 'Epoch 5', 'Epoch 6', 'Epoch 7', 'Epoch 8', 'Epoch 9', 'Epoch 10']
r2 = ['Train loss', 'Valid loss']
rows_losses = pd.MultiIndex.from_product((r1, r2))

cols = [('ChIP-seq',    'control',  'CTCF'),
        ('ChIP-seq',    'control', 'FOSL2'),
        ('ChIP-seq', 'no control',  'CTCF'),
        ('ChIP-seq', 'no control', 'FOSL2'),
        ( 'CUT&RUN', 'no control',  'CTCF'),
        ( 'CUT&RUN', 'no control', 'FOSL2')]
cols = pd.MultiIndex.from_tuples(cols)

metrics = pd.DataFrame(index=rows_metrics, columns=cols)
losses = pd.DataFrame(index=rows_losses, columns=cols)

In [ ]:
chipseq_1 = {}

In [ ]:
for task in ['CTCF', 'FOSL2']:
    assert get_tasks_path() == 'data/chip-seq/'
    #assert get_tasks_path() == 'data/cutnrun/'
    set_dataloaders(*dl_dict[task])
    METRICS, LOSS_LIST = evaluate([task], [task], [task], 1, controls=False, epoch_metrics=True, 
      model_save_path=f'/home/katie/bp_repo/research/trained_models/{task}_1_epoch_chip_seq_AUG2.model')
    chipseq_1[(task, 'metrics')], chipseq_1[(task, 'losses')] = METRICS, LOSS_LIST

In [ ]:
metrics.to_pickle('/home/katie/bp_repo/research/metrics/AUG1.pickle')
metrics.to_csv('/home/katie/bp_repo/research/metrics/AUG1.csv')

In [ ]:
########################################

In [ ]:
## multi-task evaluation for CUT&RUN data

# initialize metrics DataFrame
row_names = ['Train task', 'Valid task', 'Test task',
            'Train epoch 1 loss', 'Valid epoch 1 loss','Train epoch 2 loss',
            'Valid epoch 2 loss','Train epoch 3 loss','Valid epoch 3 loss',
            'Train epoch 4 loss','Valid epoch 4 loss','Train epoch 5 loss',
            'Valid epoch 5 loss','Train epoch 6 loss','Valid epoch 6 loss',
            'Train epoch 7 loss','Valid epoch 7 loss','Train epoch 8 loss',
            'Valid epoch 8 loss','Train epoch 9 loss','Valid epoch 9 loss',
            'Train epoch 10 loss','Valid epoch 10 loss',
            'Test profile NLL','Test profile cross entropy','Test profile JSD',
            'Test profile Pearson','Test profile Spearman','Test profile MSE',
            'Test count Pearson','Test count Spearman','Test count MSE']

metrics = pd.DataFrame(data=row_names,columns=['Metrics'])

# the "SPI1_copy" and "GATA2_copy" tasks are there for a control - you train a
# multi-task model but the data is redundant, so you should get metrics similar
# to the single-task version
train_tasks = [ ['SPI1', 'SPI1_copy'], ['GATA2', 'GATA2_copy'], ['SPI1','GATA2'] ]
val_tasks = [ ['SPI1', 'SPI1_copy'], ['GATA2', 'GATA2_copy'], ['SPI1','GATA2'] ]
test_tasks = [['SPI1', 'GATA2']]

num_permutations = len(train_tasks) * len(val_tasks) * len(test_tasks)

for train_task in train_tasks:
    for val_task in val_tasks:
        for test_task in test_tasks:
            combined_loss_and_metrics = evaluate(train_task, val_task, test_task, 2,
  model_save_path=f'/home/katie/bp_repo/multitask_profile_model_example/trained_models/train_{train_task[0]}_{train_task[1]}_val_{val_task[0]}_{val_task[1]}.model')
            metrics.insert( 1, str(num_permutations), combined_loss_and_metrics )
            num_permutations -= 1
            
metrics.set_index('Metrics',inplace=True)

# save as csv! to load it in, can use pd.read_csv(path)
metrics.to_csv('/home/katie/bp_repo/multitask_profile_model_example/performance_metrics/multi_task_metrics_ATTEMPT2.csv')